### ISSUE TITLE
Error during Docker build

### ISSUE THREAD

**Issue by cgeller** [DLR-TS/Carla-OSI-Service#3]
Hi, I tried to build the carla-osi-service Docker image with `docker build .` but got the following error. It seems like the [options] in the conanfile are not working?
```
#0 1.059 ERROR: Error while parsing [options] in conanfile
#0 1.059 Options should be specified as 'pkg:option=value'
#0 1.081 CMake Error at build/conan.cmake:522 (message):
#0 1.081   Conan install failed='1'
#0 1.081 Call Stack (most recent call first):
#0 1.081   build/conan.cmake:759 (old_conan_cmake_install)
#0 1.081   CMakeLists.txt:44 (conan_cmake_run)
#0 1.081 
#0 1.081 
#0 1.081 -- Configuring incomplete, errors occurred!
#0 1.081 See also "/carlaosiservice/build/CMakeFiles/CMakeOutput.log".
------
Dockerfile:13
--------------------
  11 |     COPY . /carlaosiservice/
  12 |     
  13 | >>> RUN cmake .. -DCMAKE_BUILD_TYPE=Release
  14 |     RUN cmake --build . --target CARLA_OSI_Service -j 8
  15 |     
--------------------
```
Can anybody help?

**Comment by cgeller** [comment]
@bjoernbahn I have the same problem also when building `osmp` or `cosima`. Can you help us here?

**Comment by frankbaumgarten** [comment]
We tried to reproduce the error but could not get the same error message but it looks like its the conan version. They updated to conan 2.0.0 in the pip repo on 2023-02-22. 

@cgeller Please try to change Dockerfile line `pip install conan` to `pip install conan==1.59.0`

**Comment by cgeller** [comment]
This helped a lot! The build is now successful. Thank you
